using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerController : MonoBehaviour
{
    // Movement Variables references
    [Header("Base setup")]
    public float walkingSpeed = 7.5f;
    public float runningSpeed = 11.5f;
    public float jumpSpeed = 8.0f;
    public float gravity = 20.0f;
    public float lookSpeed = 2.0f;
    public float lookXLimit = 45.0f;

    // Character controller reference
    public CharacterController characterController;
    Vector3 moveDirection = Vector3.zero;
    float rotationX = 0;

    [HideInInspector]
    public bool canMove = true;

    //camera transfrom reference
    public Transform cameraTransfrom;

    // visor reference
    [SerializeField]
    private GameObject visor;

    // Shoot script reference
    [SerializeField]
    public RayCastShoot rayCastShoot;

    // Player Health reference
    [SerializeField]
    private PlayerHealth playerHealth;

    void Start()
    {
        // disable visor for this client.
        visor.SetActive(false);

        // Lock cursor
        Cursor.lockState = CursorLockMode.Locked;
        Cursor.visible = false;
    }

    void FixedUpdate()
    {
        /*   // Invoke death if player health <= 0
        if (playerHealth.health <= 0)
        {
            Invoke(nameof(Death), 0.5f);
        }   */

        bool isRunning = false;

        // Press Left Shift to run
        isRunning = Input.GetKey(KeyCode.LeftShift);

        // We are grounded, so recalculate move direction based on axis
        Vector3 forward = transform.TransformDirection(Vector3.forward);
        Vector3 right = transform.TransformDirection(Vector3.right);

        float curSpeedX = canMove ? (isRunning ? runningSpeed : walkingSpeed) * Input.GetAxis("Vertical") : 0;
        float curSpeedY = canMove ? (isRunning ? runningSpeed : walkingSpeed) * Input.GetAxis("Horizontal") : 0;
        float movementDirectionY = moveDirection.y;
        moveDirection = (forward * curSpeedX) + (right * curSpeedY);

        // Jump
        if (Input.GetButton("Jump") && canMove && characterController.isGrounded)
        {
            moveDirection.y = jumpSpeed;
        }
        else
        {
            moveDirection.y = movementDirectionY;
        }

        // Gravity
        if (!characterController.isGrounded)
        {
            moveDirection.y -= gravity * Time.deltaTime;
        }

        // Move the controller
        characterController.Move(moveDirection * Time.deltaTime);

        // Player rotation
        if (canMove)
        {
            rotationX += -Input.GetAxis("Mouse Y") * lookSpeed;
            rotationX = Mathf.Clamp(rotationX, -lookXLimit, lookXLimit);
            transform.rotation *= Quaternion.Euler(0, Input.GetAxis("Mouse X") * lookSpeed, 0);
        }

        // Mouse0 (Left Click) to shoot
        if (Input.GetKey(KeyCode.Mouse0) && !isRunning && characterController.isGrounded)
        {
            rayCastShoot.Shoot();
            ClientSend.PlayerShoot();
        }

        // Send input to server
        ClientSend.PlayerMovement();
    }

    /// <summary>
    /// Destroy this gameObject on death.
    /// </summary>
    private void Death()
    {
        Destroy(this.gameObject);
    }
}
